import { z } from "zod";

export const PROJECT_MANAGER_COMPANY_NAME = "1001328662 Ontario Inc.";
export const PROJECT_MANAGER_AGREEMENT_TYPE = "PROJECT_MANAGER_SERVICES_AGREEMENT";
export const PROJECT_MANAGER_APPLICATION_TYPE = "PROJECT_MANAGER";
export const PROJECT_MANAGER_AGREEMENT_TITLE = "PROJECT MANAGER INDEPENDENT SERVICES AGREEMENT";
export const PROJECT_MANAGER_AGREEMENT_VERSION = "DRAFT-1.0";
export const projectManagerApplicationPayloadSchema = z.object({ entityType: z.enum(["CORPORATION", "SOLE_PROPRIETOR", "PARTNERSHIP", "OTHER"]), legalBusinessName: z.string().trim().min(2).max(200), operatingName: z.string().trim().max(200).optional().nullable(), corporationNumber: z.string().trim().max(100).optional().nullable(), taxNumber: z.string().trim().max(100).optional().nullable(), contactLegalName: z.string().trim().min(2).max(200), contactTitle: z.string().trim().max(100).optional().nullable(), email: z.string().trim().email().max(254), phone: z.string().trim().min(7).max(40), address: z.string().trim().min(4).max(300), city: z.string().trim().min(2).max(100), province: z.string().trim().min(2).max(100), postalCode: z.string().trim().min(3).max(20), businessDescription: z.string().trim().max(3000).optional().nullable(), workers: z.array(z.object({ legalName: z.string().trim().min(2).max(200), relationshipType: z.enum(["EMPLOYEE", "INDEPENDENT_CONTRACTOR", "SUBCONTRACTOR_OF_OTHER_ENTITY", "OWNER", "OTHER"]), role: z.string().trim().max(120).optional().nullable(), email: z.string().trim().email().optional().nullable(), phone: z.string().trim().max(40).optional().nullable(), workEligibilityConfirmed: z.boolean() })).max(100).default([]) });
export const PROJECT_MANAGER_LEGAL_REVIEW_NOTICE = "Draft for Legal Review. This document requires review by qualified Canadian legal counsel before production use.";
export const PROJECT_MANAGER_STATUS_NOTICE = "\"Project Manager\" is an operational title. Legal status depends on the actual working relationship and applicable law.";
export type ProjectManagerAgreementSection = { id: string; title: string; paragraphs: string[] };
export const projectManagerAcknowledgments = [
  { key: "legal-review", text: "I understand that this agreement is labelled Draft for Legal Review and requires qualified Canadian legal review." },
  { key: "operational-title", text: "I understand that Project Manager is an operational title and legal status depends on the actual working relationship and applicable law." },
  { key: "no-guarantee", text: "I understand that no projects, hours, revenue, rate, payment period, or worker acceptance is guaranteed." },
  { key: "worker-relationships", text: "I confirm that each worker's actual legal relationship will be accurately disclosed and all worker-related legal and statutory obligations will be met." },
  { key: "statutory-rights", text: "I understand that nothing in this agreement waives or limits rights or obligations that cannot lawfully be waived." },
] as const;
export const projectManagerAgreementSections: ProjectManagerAgreementSection[] = [
  { id: "parties", title: "1. Parties and Purpose", paragraphs: ["This Project Manager Independent Services Agreement is entered into between 1001328662 Ontario Inc. (the \"Company\") and the Project Manager.", "The Project Manager is the approved legal business entity identified in Schedule A. The parties intend to document independent business services, subject always to the actual working relationship and applicable law."] },
  { id: "relationship", title: "2. Relationship and Operational Title", paragraphs: ["\"Project Manager\" is an operational title only. It does not by itself determine whether any person is an employee, dependent contractor, independent contractor, agent, partner, or other legal category.", "The legal status of the Project Manager and every worker depends on the actual facts, the working relationship, and applicable law. Nothing in this Agreement waives statutory rights or obligations.", "The Project Manager has no authority to bind the Company unless expressly authorized in writing for a specific purpose."] },
  { id: "no-guarantee", title: "3. No Guaranteed Work or Revenue", paragraphs: ["The Company does not guarantee projects, assignments, hours, revenue, worker acceptance, exclusivity, continuity, or any minimum volume of work.", "The Project Manager may accept or decline an Assignment Confirmation. A project exists only when the parties issue and accept a project-specific Assignment Confirmation."] },
  { id: "responsibilities", title: "4. Project Manager Responsibilities", paragraphs: ["The Project Manager will organize and coordinate qualified workers for accepted projects, communicate project requirements, maintain accurate records, monitor completion, and promptly report safety, quality, attendance, privacy, or client concerns.", "The Project Manager will not misrepresent worker qualifications, legal status, availability, hours, or project completion."] },
  { id: "workers", title: "5. Worker Roster and Legal Relationships", paragraphs: ["Before a worker is proposed or assigned, the Project Manager must maintain the approved roster in Schedule B and accurately identify each worker's actual legal relationship to the Project Manager or another responsible entity.", "The Company may approve or reject a proposed worker for project, qualification, client, safety, security, or compliance reasons. Approval does not transfer the Project Manager's obligations and is not a guarantee that the worker will accept or receive work."] },
  { id: "payment-compliance", title: "6. Worker Payment and Statutory Compliance", paragraphs: ["The Project Manager is responsible for all payment, payroll, deductions, remittances, source deductions, vacation pay, overtime, public holiday obligations, workers' compensation obligations, benefits, records of employment, and other statutory duties that apply to its actual relationships with workers.", "The Project Manager must not characterize a worker inaccurately or require a worker to waive a non-waivable statutory right."] },
  { id: "licensing", title: "7. Licensing, Insurance, and Compliance", paragraphs: ["The Project Manager will maintain all registrations, licences, permits, insurance, clearances, training, background checks, and compliance documents required by law, the applicable Assignment Confirmation, or a client site.", "Current documents are listed in Schedule E. Expiry, suspension, cancellation, or material change must be reported immediately."] },
  { id: "health-safety", title: "8. Health and Safety", paragraphs: ["Each party will comply with applicable occupational health and safety law. The Project Manager will ensure workers receive required information, instruction, supervision, personal protective equipment, and site-specific orientation appropriate to the actual legal relationship.", "Unsafe work, incidents, injuries, hazards, violence, harassment, and regulatory contact must be reported promptly. No person will be penalized for exercising a lawful health and safety right."] },
  { id: "timekeeping", title: "9. Timekeeping and Records", paragraphs: ["The Project Manager will ensure complete and accurate project, attendance, time, break, approval, and correction records. Falsified, duplicate, proxy, or misleading records are prohibited.", "Only verified project records will be considered for invoicing. Timekeeping requirements do not create a universal rate or payment period."] },
  { id: "commercial", title: "10. Rates, Invoicing, Payment, and Cancellation", paragraphs: ["Rates, taxes, invoice requirements, approval conditions, payment timing, holdbacks if lawful, expenses, cancellation terms, and insurance requirements are configurable and must be stated in Schedule D or the applicable Assignment Confirmation.", "There is no universal rate and no payment period is implied or invented. Inconsistent terms must be resolved in writing before work begins."] },
  { id: "confidentiality", title: "11. Confidentiality, Privacy, and Security", paragraphs: ["The Project Manager will protect confidential information and personal information, use it only for authorized project purposes, restrict access to those who need it, and follow Schedule F.", "Actual or suspected loss, unauthorized access, disclosure, misuse, or security incident must be reported immediately. Confidential information must be returned or securely destroyed when no longer required, subject to lawful retention duties."] },
  { id: "non-solicitation", title: "12. Limited Non-Solicitation and Non-Circumvention", paragraphs: ["Only the duration, persons, clients, projects, geography, prohibited conduct, exceptions, and remedies expressly configured in Schedule D apply. Any restriction must be narrow, reasonable, connected to legitimate interests, and interpreted to comply with applicable law.", "No restriction prohibits lawful competition, general advertising, pre-existing relationships disclosed in writing, worker-protected activity, or the exercise of a statutory right."] },
  { id: "suspension-termination", title: "13. Suspension and Termination", paragraphs: ["The Company may suspend access, worker approvals, project offers, or an Assignment Confirmation while investigating safety, compliance, privacy, fraud, quality, insurance, client, or legal concerns.", "Either party may terminate this Agreement on the configured notice in Schedule D. Immediate termination may occur for material breach, unlawful conduct, serious safety risk, fraud, confidentiality or privacy breach, loss of required licensing or insurance, or insolvency, subject to applicable law.", "Termination does not affect accrued payment obligations, confidentiality, privacy, audit, dispute, liability, or other provisions intended to survive."] },
  { id: "disputes-liability", title: "14. Disputes and Liability", paragraphs: ["The parties will first attempt good-faith business resolution. Any mediation, arbitration, court venue, governing law, indemnity, insurance allocation, limitation, or exclusion must be configured in Schedule D and remains subject to applicable law.", "Nothing excludes liability or remedies that cannot lawfully be excluded, limits statutory rights, or excuses payment of amounts legally owing."] },
  { id: "electronic", title: "15. Electronic Signatures and Audit Trail", paragraphs: ["The parties consent to electronic records and signatures. Separate acknowledgments, views, signatures, countersignatures, timestamps, IP information, user-agent information, document hashes, version history, and related events may form the audit trail.", "An executed version is immutable. It will never be overwritten. An amendment, replacement, or superseding agreement must create a new version or record while preserving the executed document and audit history."] },
  { id: "general", title: "16. General", paragraphs: ["This Agreement, its selected schedules, accepted Assignment Confirmations, and written amendments form the agreement between the parties for their subject matter.", "If a provision conflicts with mandatory law, mandatory law prevails and the remaining provisions continue to the extent lawful. No failure to enforce is a waiver. Notices may be delivered through the secure portal or other configured method."] },
];
export const projectManagerScheduleLabels = { A: "Business Information", B: "Approved Worker Roster", C: "Assignment Confirmation", D: "Rates and Payment Terms", E: "Insurance/Licensing Documents", F: "Privacy and Security Requirements" } as const;
export function createProjectManagerAgreementBody(): string { return projectManagerAgreementSections.map(section => `${section.title}\n${section.paragraphs.join("\n\n")}`).join("\n\n"); }
