import { sql } from "drizzle-orm";
import { boolean, date, index, integer, pgTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core";

export const projectManagerApplications = pgTable("project_manager_applications", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  applicationNumber: text("application_number").notNull().unique(), applicationType: text("application_type").notNull().default("PROJECT_MANAGER"),
  entityType: text("entity_type").notNull(), legalBusinessName: text("legal_business_name").notNull(), operatingName: text("operating_name"), corporationNumber: text("corporation_number"), taxNumber: text("tax_number"),
  contactLegalName: text("contact_legal_name").notNull(), contactTitle: text("contact_title"), email: text("email").notNull(), phone: text("phone").notNull(), address: text("address").notNull(), city: text("city").notNull(), province: text("province").notNull(), postalCode: text("postal_code").notNull(), businessDescription: text("business_description"),
  status: text("status").notNull().default("SUBMITTED"), adminNotes: text("admin_notes"), reviewedBy: varchar("reviewed_by"), reviewedAt: timestamp("reviewed_at"), conditionallyApprovedAt: timestamp("conditionally_approved_at"), executedAgreementId: varchar("executed_agreement_id"), portalTokenHash: text("portal_token_hash"), portalTokenExpiresAt: timestamp("portal_token_expires_at"), submittedIp: text("submitted_ip"), submittedUserAgent: text("submitted_user_agent"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, table => ({ emailIdx: index("project_manager_applications_email_idx").on(table.email), statusIdx: index("project_manager_applications_status_idx").on(table.status) }));

export const projectManagerWorkers = pgTable("project_manager_workers", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`), applicationId: varchar("application_id").notNull().references(() => projectManagerApplications.id), legalName: text("legal_name").notNull(), relationshipType: text("relationship_type").notNull(), role: text("role"), email: text("email"), phone: text("phone"), workEligibilityConfirmed: boolean("work_eligibility_confirmed").notNull().default(false), status: text("status").notNull().default("PROPOSED"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, table => ({ applicationIdx: index("project_manager_workers_application_idx").on(table.applicationId) }));

export const projectManagerDocuments = pgTable("project_manager_documents", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`), applicationId: varchar("application_id").notNull().references(() => projectManagerApplications.id), category: text("category").notNull(), originalFileName: text("original_file_name").notNull(), storageKey: text("storage_key").notNull(), encryptedContent: text("encrypted_content").notNull(), mimeType: text("mime_type").notNull(), sha256: text("sha256").notNull(), expiresAt: timestamp("expires_at"), status: text("status").notNull().default("UPLOADED"), uploadedBy: text("uploaded_by").notNull(), createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({ applicationIdx: index("project_manager_documents_application_idx").on(table.applicationId) }));

export const projectManagerAgreements = pgTable("project_manager_agreements", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`), applicationId: varchar("application_id").notNull().references(() => projectManagerApplications.id), agreementNumber: text("agreement_number").notNull().unique(), agreementType: text("agreement_type").notNull().default("PROJECT_MANAGER_SERVICES_AGREEMENT"), status: text("status").notNull().default("Not Generated"), currentVersionId: varchar("current_version_id"), executedVersionId: varchar("executed_version_id"), supersedesAgreementId: varchar("supersedes_agreement_id"), suspendedAt: timestamp("suspended_at"), cancelledAt: timestamp("cancelled_at"), createdBy: varchar("created_by"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, table => ({ applicationIdx: index("project_manager_agreements_application_idx").on(table.applicationId), statusIdx: index("project_manager_agreements_status_idx").on(table.status) }));

export const projectManagerAgreementVersions = pgTable("project_manager_agreement_versions", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`), agreementId: varchar("agreement_id").notNull().references(() => projectManagerAgreements.id), versionNumber: integer("version_number").notNull(), title: text("title").notNull().default("PROJECT MANAGER INDEPENDENT SERVICES AGREEMENT"), bodySnapshot: text("body_snapshot").notNull(), schedulesSnapshot: text("schedules_snapshot").notNull(), commercialTermsSnapshot: text("commercial_terms_snapshot").notNull(), contentSha256: text("content_sha256").notNull(), isExecuted: boolean("is_executed").notNull().default(false), finalPdfBase64: text("final_pdf_base64"), finalPdfSha256: text("final_pdf_sha256"), executedAt: timestamp("executed_at"), createdBy: varchar("created_by"), createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({ agreementVersionUnique: uniqueIndex("project_manager_agreement_version_unique").on(table.agreementId, table.versionNumber) }));

export const projectManagerAcknowledgments = pgTable("project_manager_acknowledgments", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`), agreementVersionId: varchar("agreement_version_id").notNull().references(() => projectManagerAgreementVersions.id), applicationId: varchar("application_id").notNull().references(() => projectManagerApplications.id), acknowledgmentKey: text("acknowledgment_key").notNull(), acknowledgmentText: text("acknowledgment_text").notNull(), accepted: boolean("accepted").notNull(), acceptedAt: timestamp("accepted_at").notNull(), ip: text("ip"), userAgent: text("user_agent"),
}, table => ({ versionKeyUnique: uniqueIndex("project_manager_ack_version_key_unique").on(table.agreementVersionId, table.acknowledgmentKey) }));

export const projectManagerSignatures = pgTable("project_manager_signatures", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`), agreementVersionId: varchar("agreement_version_id").notNull().references(() => projectManagerAgreementVersions.id), signerRole: text("signer_role").notNull(), signerLegalName: text("signer_legal_name").notNull(), signerTitle: text("signer_title"), signatureText: text("signature_text").notNull(), signedAt: timestamp("signed_at").notNull(), ip: text("ip"), userAgent: text("user_agent"), signatureSha256: text("signature_sha256").notNull(),
}, table => ({ versionRoleUnique: uniqueIndex("project_manager_signature_version_role_unique").on(table.agreementVersionId, table.signerRole) }));

export const projectManagerSigningLinks = pgTable("project_manager_signing_links", { id: varchar("id").primaryKey().default(sql`gen_random_uuid()`), agreementVersionId: varchar("agreement_version_id").notNull().references(() => projectManagerAgreementVersions.id), tokenHash: text("token_hash").notNull().unique(), purpose: text("purpose").notNull(), expiresAt: timestamp("expires_at").notNull(), firstViewedAt: timestamp("first_viewed_at"), completedAt: timestamp("completed_at"), revokedAt: timestamp("revoked_at"), createdBy: varchar("created_by"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const projectManagerAssignments = pgTable("project_manager_assignments", { id: varchar("id").primaryKey().default(sql`gen_random_uuid()`), applicationId: varchar("application_id").notNull().references(() => projectManagerApplications.id), agreementId: varchar("agreement_id").notNull().references(() => projectManagerAgreements.id), assignmentNumber: text("assignment_number").notNull().unique(), status: text("status").notNull().default("DRAFT"), projectName: text("project_name").notNull(), clientSite: text("client_site"), scope: text("scope").notNull(), startDate: date("start_date"), endDate: date("end_date"), ratesSnapshot: text("rates_snapshot").notNull(), termsSnapshot: text("terms_snapshot").notNull(), workerIdsSnapshot: text("worker_ids_snapshot").notNull(), pdfBase64: text("pdf_base64"), pdfSha256: text("pdf_sha256"), issuedAt: timestamp("issued_at"), acceptedAt: timestamp("accepted_at"), createdBy: varchar("created_by"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const projectManagerNotices = pgTable("project_manager_notices", { id: varchar("id").primaryKey().default(sql`gen_random_uuid()`), applicationId: varchar("application_id").notNull().references(() => projectManagerApplications.id), agreementId: varchar("agreement_id").references(() => projectManagerAgreements.id), noticeType: text("notice_type").notNull(), subject: text("subject").notNull(), body: text("body").notNull(), acknowledgedAt: timestamp("acknowledged_at"), createdBy: varchar("created_by"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const projectManagerAuditLog = pgTable("project_manager_audit_log", { id: varchar("id").primaryKey().default(sql`gen_random_uuid()`), applicationId: varchar("application_id").references(() => projectManagerApplications.id), agreementId: varchar("agreement_id").references(() => projectManagerAgreements.id), agreementVersionId: varchar("agreement_version_id").references(() => projectManagerAgreementVersions.id), actorType: text("actor_type").notNull(), actorId: text("actor_id"), eventType: text("event_type").notNull(), metadata: text("metadata").notNull().default("{}"), ip: text("ip"), userAgent: text("user_agent"), previousHash: text("previous_hash"), eventHash: text("event_hash").notNull(), createdAt: timestamp("created_at").defaultNow().notNull() }, table => ({ agreementIdx: index("project_manager_audit_agreement_idx").on(table.agreementId), applicationIdx: index("project_manager_audit_application_idx").on(table.applicationId) }));
