import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { PROJECT_MANAGER_AGREEMENT_TITLE, PROJECT_MANAGER_COMPANY_NAME, PROJECT_MANAGER_LEGAL_REVIEW_NOTICE, PROJECT_MANAGER_STATUS_NOTICE, createProjectManagerAgreementBody, projectManagerAcknowledgments, projectManagerApplicationPayloadSchema, projectManagerScheduleLabels } from "../shared/project-manager-agreement-content";
import { createProjectAssignmentPdf, createProjectManagerAgreementPdf, createProjectManagerApplicationPdf, projectAssignmentFileName, projectManagerAgreementFileName, projectManagerApplicationFileName, sha256Buffer } from "../server/lib/project-manager-pdf";

async function main() {
  const fiveWorkers = Array.from({ length: 5 }, (_, index) => ({ legalName: `Worker ${index + 1}`, relationshipType: index % 2 ? "EMPLOYEE" as const : "INDEPENDENT_CONTRACTOR" as const, role: "Project Worker", email: `worker${index + 1}@example.test`, phone: `416555010${index}`, workEligibilityConfirmed: true }));
  const baseApplication = { legalBusinessName: "Example Project Services", operatingName: null, corporationNumber: null, taxNumber: null, contactLegalName: "Alex Example", contactTitle: "Owner", email: "alex@example.test", phone: "4165550100", address: "1 Example Street", city: "Toronto", province: "Ontario", postalCode: "M5V 1A1", businessDescription: "Coordinates project workers.", workers: fiveWorkers };
  const corporation = projectManagerApplicationPayloadSchema.parse({ ...baseApplication, entityType: "CORPORATION", corporationNumber: "1234567" });
  const soleProprietor = projectManagerApplicationPayloadSchema.parse({ ...baseApplication, entityType: "SOLE_PROPRIETOR", legalBusinessName: "Alex Example", corporationNumber: null });
  assert.equal(corporation.workers.length, 5); assert.equal(soleProprietor.entityType, "SOLE_PROPRIETOR"); assert.equal(PROJECT_MANAGER_COMPANY_NAME, "1001328662 Ontario Inc."); assert.equal(PROJECT_MANAGER_AGREEMENT_TITLE, "PROJECT MANAGER INDEPENDENT SERVICES AGREEMENT"); assert.match(PROJECT_MANAGER_LEGAL_REVIEW_NOTICE, /qualified Canadian legal/i); assert.match(PROJECT_MANAGER_STATUS_NOTICE, /operational title/i); assert.deepEqual(Object.keys(projectManagerScheduleLabels), ["A", "B", "C", "D", "E", "F"]); assert.equal(projectManagerAcknowledgments.length, 5);
  const prohibitedBrandPattern = new RegExp([["Workforce", "Connect"].join(" "), ["WF", "Connect"].join(""), ["M", "MJ"].join("")].join("|"), "i");
  assert.doesNotMatch(createProjectManagerAgreementBody(), prohibitedBrandPattern);
  const commercialTerms = { rateTerms: "Project-specific rate: $42.75 per approved hour for this test only.", invoicingTerms: "Invoice after project acceptance.", paymentTerms: "Net 21 for this test project only.", insuranceTerms: "Commercial general liability as configured.", cancellationTerms: "Twenty-four hours for this test project.", terminationNotice: "Configured notice.", disputeTerms: "Good-faith negotiation.", liabilityTerms: "Subject to applicable law.", nonSolicitationDuration: "Three months", nonSolicitationTerms: "Limited to the named project client and direct circumvention." };
  const agreementPdf = await createProjectManagerAgreementPdf({ agreementNumber: "PMA-TEST-001", versionNumber: 1, application: corporation, schedules: { A: corporation, B: fiveWorkers, C: { reusable: true }, D: commercialTerms, E: { insurance: "Configured" }, F: { privacy: "Configured" } }, commercialTerms, acknowledgments: projectManagerAcknowledgments.map(item => ({ acknowledgmentText: item.text, accepted: true, acceptedAt: new Date().toISOString() })), signatures: [{ signerRole: "PROJECT_MANAGER", signerLegalName: "Alex Example", signerTitle: "Owner", signatureText: "Alex Example", signedAt: new Date().toISOString(), signatureSha256: "a".repeat(64) }, { signerRole: "COMPANY", signerLegalName: "Company Signer", signerTitle: "Authorized Signer", signatureText: "Company Signer", signedAt: new Date().toISOString(), signatureSha256: "b".repeat(64) }] });
  assert.ok(agreementPdf.length > 5000); assert.equal(sha256Buffer(agreementPdf).length, 64); assert.equal(projectManagerAgreementFileName("PMA-TEST-001"), "Project-Manager-Agreement-PMA-TEST-001.pdf");
  const assignmentPdf = await createProjectAssignmentPdf({ assignmentNumber: "PA-TEST-001", projectName: "Test Project", clientSite: "Test Site", scope: "Coordinate a five-worker roster.", startDate: "2026-06-15", endDate: "2026-06-20", rates: commercialTerms, terms: { cancellation: "Project-specific" }, workers: fiveWorkers });
  assert.ok(assignmentPdf.length > 1500); assert.equal(projectAssignmentFileName("PA-TEST-001"), "Project-Assignment-PA-TEST-001.pdf");
  const applicationPdf = await createProjectManagerApplicationPdf({ applicationNumber: "PMA-APP-001", application: corporation, workers: fiveWorkers });
  assert.ok(applicationPdf.length > 1500); assert.equal(projectManagerApplicationFileName("PMA-APP-001"), "Project-Manager-Application-PMA-APP-001.pdf");
  const root = process.cwd(); const projectFiles = ["server/project-manager-routes.ts", "server/lib/project-manager-pdf.ts", "shared/project-manager-agreement-content.ts", "server/templates/project-manager-apply.html", "server/templates/project-manager-sign.html", "server/templates/project-manager-admin.html", "server/templates/project-manager-portal.html"].map(file => fs.readFileSync(path.join(root, file), "utf8")).join("\n");
  assert.doesNotMatch(projectFiles, prohibitedBrandPattern); assert.match(projectFiles, /PROJECT_MANAGER_DOCUMENT_KEY/); assert.match(projectFiles, /aes-256-gcm/); assert.match(projectFiles, /expiresAt <= new Date\(\)/); assert.match(projectFiles, /Authorized administrator access required/);
  const migration = fs.readFileSync(path.join(root, "migrations/0011_project_manager_workflow.sql"), "utf8"); assert.match(migration, /prevent_project_manager_executed_version_mutation/); assert.match(migration, /BEFORE UPDATE OR DELETE/); assert.match(migration, /project_manager_signing_links/); assert.match(migration, /project_manager_audit_log/);
  console.log("Project Manager workflow tests passed.");
}
main().catch(error => { console.error(error); process.exitCode = 1; });
