import PDFDocument from "pdfkit";
import crypto from "node:crypto";
import { PROJECT_MANAGER_AGREEMENT_TITLE, PROJECT_MANAGER_COMPANY_NAME, PROJECT_MANAGER_LEGAL_REVIEW_NOTICE, PROJECT_MANAGER_STATUS_NOTICE, projectManagerAgreementSections, projectManagerScheduleLabels } from "../../shared/project-manager-agreement-content";
type PdfData={agreementNumber:string;versionNumber:number;application:Record<string,any>;schedules:Record<string,any>;commercialTerms:Record<string,any>;acknowledgments?:Array<Record<string,any>>;signatures?:Array<Record<string,any>>};
const value=(v:unknown):string=>v===null||v===undefined||v===""?"Not specified":Array.isArray(v)?v.map(String).join(", "):typeof v==="object"?JSON.stringify(v,null,2):String(v);
function ensureSpace(doc:PDFKit.PDFDocument,height=90){if(doc.y+height>doc.page.height-55)doc.addPage()}
function heading(doc:PDFKit.PDFDocument,text:string){ensureSpace(doc);doc.font("Helvetica-Bold").fontSize(12).fillColor("#111827").text(text);doc.moveDown(.35)}
function paragraph(doc:PDFKit.PDFDocument,text:string){doc.font("Helvetica").fontSize(9.2).fillColor("#1f2937").text(text,{lineGap:2});doc.moveDown(.45)}
function footer(doc:PDFKit.PDFDocument){const range=doc.bufferedPageRange();for(let page=range.start;page<range.start+range.count;page++){doc.switchToPage(page);doc.font("Helvetica").fontSize(8).fillColor("#6b7280").text(`\u00A9 ${PROJECT_MANAGER_COMPANY_NAME}. All rights reserved.`,55,doc.page.height-38,{align:"center",width:doc.page.width-110})}}
async function finish(doc:PDFKit.PDFDocument,chunks:Buffer[]){footer(doc);doc.end();await new Promise<void>((resolve,reject)=>{doc.on("end",resolve);doc.on("error",reject)});return Buffer.concat(chunks)}
export async function createProjectManagerAgreementPdf(data:PdfData):Promise<Buffer>{const doc=new PDFDocument({size:"LETTER",margins:{top:48,bottom:55,left:55,right:55},bufferPages:true,info:{Title:`${PROJECT_MANAGER_AGREEMENT_TITLE} ${data.agreementNumber}`,Author:PROJECT_MANAGER_COMPANY_NAME,Subject:PROJECT_MANAGER_LEGAL_REVIEW_NOTICE}});const chunks:Buffer[]=[];doc.on("data",chunk=>chunks.push(Buffer.from(chunk)));doc.font("Helvetica-Bold").fontSize(12).fillColor("#111827").text(PROJECT_MANAGER_COMPANY_NAME,{align:"center"});doc.moveDown(.7);doc.fontSize(16).text(PROJECT_MANAGER_AGREEMENT_TITLE,{align:"center"});doc.moveDown(.35);doc.font("Helvetica").fontSize(9).fillColor("#4b5563").text(`Agreement ${data.agreementNumber} | Version ${data.versionNumber}`,{align:"center"});doc.moveDown(1);doc.roundedRect(55,doc.y,doc.page.width-110,82,4).fillAndStroke("#f3f4f6","#9ca3af");const y=doc.y+12;doc.font("Helvetica-Bold").fontSize(12).fillColor("#111827").text("Draft for Legal Review",70,y,{width:doc.page.width-140,align:"center"});doc.font("Helvetica").fontSize(9).fillColor("#374151").text(PROJECT_MANAGER_LEGAL_REVIEW_NOTICE,70,y+22,{width:doc.page.width-140,align:"center"});doc.text(PROJECT_MANAGER_STATUS_NOTICE,70,y+46,{width:doc.page.width-140,align:"center"});doc.y=y+86;doc.moveDown(.8);projectManagerAgreementSections.forEach(section=>{heading(doc,section.title);section.paragraphs.forEach(item=>paragraph(doc,item))});Object.entries(projectManagerScheduleLabels).forEach(([key,label])=>{doc.addPage();heading(doc,`Schedule ${key} - ${label}`);const schedule=data.schedules[key]??(key==="A"?data.application:key==="D"?data.commercialTerms:{});if(Array.isArray(schedule))schedule.forEach((item,index)=>paragraph(doc,`${index+1}. ${value(item)}`));else Object.entries(schedule).forEach(([field,item])=>paragraph(doc,`${field.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase())}: ${value(item)}`));if(!Object.keys(schedule||{}).length)paragraph(doc,"Selected. Details to be completed in the applicable record.")});if(data.acknowledgments?.length||data.signatures?.length){doc.addPage();heading(doc,"Electronic Acknowledgments and Signatures");data.acknowledgments?.forEach(ack=>paragraph(doc,`[${ack.accepted?"X":" "}] ${ack.acknowledgmentText} Accepted: ${value(ack.acceptedAt)}`));data.signatures?.forEach(signature=>{heading(doc,signature.signerRole==="PROJECT_MANAGER"?"Project Manager Signature":"Company Countersignature");paragraph(doc,`Signed by: ${signature.signerLegalName}`);paragraph(doc,`Title: ${value(signature.signerTitle)}`);paragraph(doc,`Electronic signature: ${signature.signatureText}`);paragraph(doc,`Signed at: ${value(signature.signedAt)}`);paragraph(doc,`Signature record hash: ${signature.signatureSha256}`)})}return finish(doc,chunks)}
export const projectManagerAgreementFileName=(n:string)=>`Project-Manager-Agreement-${n}.pdf`;
export const projectAssignmentFileName=(n:string)=>`Project-Assignment-${n}.pdf`;
export const projectManagerApplicationFileName=(n:string)=>`Project-Manager-Application-${n}.pdf`;
export async function createProjectManagerApplicationPdf(data:{applicationNumber:string;application:Record<string,unknown>;workers:Array<Record<string,unknown>>}):Promise<Buffer>{const doc=new PDFDocument({size:"LETTER",margins:{top:48,bottom:55,left:55,right:55},bufferPages:true,info:{Title:`Project Manager Application ${data.applicationNumber}`,Author:PROJECT_MANAGER_COMPANY_NAME}});const chunks:Buffer[]=[];doc.on("data",chunk=>chunks.push(Buffer.from(chunk)));doc.font("Helvetica-Bold").fontSize(13).text(PROJECT_MANAGER_COMPANY_NAME,{align:"center"});doc.moveDown(.5);doc.fontSize(17).text("PROJECT MANAGER APPLICATION",{align:"center"});doc.font("Helvetica").fontSize(9).fillColor("#4b5563").text(data.applicationNumber,{align:"center"});doc.moveDown(1.2);heading(doc,"Business and Legal Information");Object.entries(data.application).filter(([key])=>!["portalTokenHash","submittedIp","submittedUserAgent"].includes(key)).forEach(([key,item])=>paragraph(doc,`${key.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase())}: ${value(item)}`));heading(doc,"Proposed Worker Roster");if(!data.workers.length)paragraph(doc,"No workers listed at submission.");data.workers.forEach((worker,index)=>paragraph(doc,`${index+1}. ${value(worker.legalName)} - actual relationship: ${value(worker.relationshipType)} - role: ${value(worker.role)}`));heading(doc,"Status Notice");paragraph(doc,PROJECT_MANAGER_STATUS_NOTICE);paragraph(doc,"Submission does not guarantee approval, projects, hours, revenue, rates, payment timing, or worker acceptance.");return finish(doc,chunks)}
export async function createProjectAssignmentPdf(data:{assignmentNumber:string;projectName:string;clientSite?:string|null;scope:string;startDate?:string|null;endDate?:string|null;rates:Record<string,unknown>;terms:Record<string,unknown>;workers:Array<Record<string,unknown>>}):Promise<Buffer>{const doc=new PDFDocument({size:"LETTER",margins:{top:48,bottom:55,left:55,right:55},bufferPages:true,info:{Title:`Project Assignment ${data.assignmentNumber}`,Author:PROJECT_MANAGER_COMPANY_NAME}});const chunks:Buffer[]=[];doc.on("data",chunk=>chunks.push(Buffer.from(chunk)));doc.font("Helvetica-Bold").fontSize(13).text(PROJECT_MANAGER_COMPANY_NAME,{align:"center"});doc.moveDown(.5);doc.fontSize(17).text("ASSIGNMENT CONFIRMATION",{align:"center"});doc.font("Helvetica").fontSize(9).fillColor("#4b5563").text(data.assignmentNumber,{align:"center"});doc.moveDown(1.2);heading(doc,"Project");paragraph(doc,`Project name: ${data.projectName}`);paragraph(doc,`Client site: ${value(data.clientSite)}`);paragraph(doc,`Dates: ${value(data.startDate)} to ${value(data.endDate)}`);heading(doc,"Scope");paragraph(doc,data.scope);heading(doc,"Project-Specific Rates");Object.entries(data.rates).forEach(([key,item])=>paragraph(doc,`${key}: ${value(item)}`));heading(doc,"Project-Specific Terms");Object.entries(data.terms).forEach(([key,item])=>paragraph(doc,`${key}: ${value(item)}`));heading(doc,"Approved Workers");if(!data.workers.length)paragraph(doc,"No workers selected at issuance.");data.workers.forEach((worker,index)=>paragraph(doc,`${index+1}. ${value(worker.legalName)} - ${value(worker.relationshipType)} - ${value(worker.role)}`));heading(doc,"No Guarantee or Waiver");paragraph(doc,"This Assignment Confirmation does not guarantee future projects, hours, revenue, worker acceptance, or any rate or payment period beyond the terms expressly stated above.");paragraph(doc,"Nothing in this Assignment Confirmation waives a statutory right or obligation.");return finish(doc,chunks)}
export const sha256Buffer=(buffer:Buffer)=>crypto.createHash("sha256").update(buffer).digest("hex");
